### PR TITLE
Feature admin status

### PR DESCRIPTION
**Pull request by mikeyrayvon**
new table layouts for Submissions and Status pages

### CODE REVIEW

**Comment by varffs** [comment]
If we are going to use table view [which is good] I think maybe the table needs to be sortable by headings, or at least name & average rating? Def needs to highlight hovered row on hover and have the entire row the clickable link.

**Comment by varffs** [comment]
Table view for Started looks good but probably needs a sophisticated sort query so applications are ordered by how many ticks? Or maybe we add created date and sort by that?

**Comment by mikeyrayvon** [comment]
Ok I'll work on that today

**Comment by mixcas** [comment]
should `npm-container`  update be on this branch? how to manage this kinda situation?

**Comment by varffs** [comment]
@mixcas no the npm thing shouldnt really it was just a weird hangover from the `meteor update` commit. basically whenever we do `meteor update` commits we need to make sure to `meteor run` before committing and pushing. my mistake

**Pull request merged**
