### PR TITLE
Feature waitlist

### PR DESCRIPTION
**Pull request by mikeyrayvon**

### CODE REVIEW

**Comment by varffs** [comment]
Can you do descriptions for PR's. Just a couple of sentences explaining added function/content

**Comment by mixcas** [comment]
@varffs r u gonna do the merge?

**Comment by varffs** [comment]
I read the code and it looks fine, but I don't think I know anything about this feature. There is nothing written about what it does or why here or on trello

**Comment by varffs** [comment]
alert-waitlist doesn't exist and so displays that string when you put something into waitlist

**Pull request merged**
